name: Build and Push Docker Image

on:
  push:
    tags:
      - "v*" # Trigger on version tags like v1.0.0, v1.2.3
    branches:
      - main # Optional: also trigger on main branch

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract version from tag
        id: vars
        run: echo "VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: |
            ghcr.io/${{ github.repository_owner }}/ip-bkd:${{ env.VERSION }}
            ghcr.io/${{ github.repository_owner }}/ip-bkd:latest
